/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ighor.view;

import com.ighor.control.CadastroDentistaControl;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Ighor Alves
 */
public class CadastroDentistaView extends javax.swing.JFrame {

    private final CadastroDentistaControl control;

    /**
     * Creates new form CadastroDentista
     */
    public CadastroDentistaView() {
        initComponents();
        control = new CadastroDentistaControl(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        txt_CadastroDentistaDataContratacao = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        btnt_CadastroDentistaCadastrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btn_CadastroDentistaLimpar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btn_CadastroDentistaFechar = new javax.swing.JButton();
        txt_CadastroDentistaNome = new javax.swing.JTextField();
        txt_CadastroDentistaNomeUsuario = new javax.swing.JTextField();
        txt_CadastroDentistaSenha = new javax.swing.JPasswordField();
        txt_CadastroDentistaSalario = new javax.swing.JTextField();
        txt_CadastroDentistaTelefone = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_CadastroDentistaCelular = new javax.swing.JFormattedTextField();
        txt_CadastroDentistaDataNascimento = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_CadastroDentistaCrm = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("Telefone:");

        jLabel7.setText("Celular:");

        btnt_CadastroDentistaCadastrar.setText("Cadastrar");
        btnt_CadastroDentistaCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnt_CadastroDentistaCadastrarActionPerformed(evt);
            }
        });

        jLabel8.setText("Data de Nascimento:");

        btn_CadastroDentistaLimpar.setText("Limpar");

        jLabel9.setText("Data de Contratação:");

        btn_CadastroDentistaFechar.setText("Fechar");
        btn_CadastroDentistaFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastroDentistaFecharActionPerformed(evt);
            }
        });

        jLabel1.setText("Cadastro de Dentista");

        jLabel2.setText("Nome Completo:");

        jLabel3.setText("Nome de Usuario:");

        jLabel4.setText("Senha:");

        jLabel5.setText("Salario:");

        jLabel10.setText("CRM:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_CadastroDentistaNome)
                            .addComponent(txt_CadastroDentistaNomeUsuario)
                            .addComponent(txt_CadastroDentistaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(txt_CadastroDentistaSalario)
                            .addComponent(txt_CadastroDentistaTelefone)
                            .addComponent(txt_CadastroDentistaCelular)
                            .addComponent(txt_CadastroDentistaDataNascimento)
                            .addComponent(txt_CadastroDentistaDataContratacao)
                            .addComponent(txt_CadastroDentistaCrm)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btnt_CadastroDentistaCadastrar)
                        .addGap(66, 66, 66)
                        .addComponent(btn_CadastroDentistaLimpar)
                        .addGap(62, 62, 62)
                        .addComponent(btn_CadastroDentistaFechar)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_CadastroDentistaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(txt_CadastroDentistaNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_CadastroDentistaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_CadastroDentistaSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_CadastroDentistaTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_CadastroDentistaCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_CadastroDentistaDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_CadastroDentistaDataContratacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_CadastroDentistaCrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnt_CadastroDentistaCadastrar)
                    .addComponent(btn_CadastroDentistaLimpar)
                    .addComponent(btn_CadastroDentistaFechar))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnt_CadastroDentistaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnt_CadastroDentistaCadastrarActionPerformed
        // TODO add your handling code here:
        control.cadastrarDentista();
    }//GEN-LAST:event_btnt_CadastroDentistaCadastrarActionPerformed

    private void btn_CadastroDentistaFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastroDentistaFecharActionPerformed
        // TODO add your handling code here:
        control.voltarMenuPrincipal();
    }//GEN-LAST:event_btn_CadastroDentistaFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDentistaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDentistaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDentistaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDentistaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDentistaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CadastroDentistaFechar;
    private javax.swing.JButton btn_CadastroDentistaLimpar;
    private javax.swing.JButton btnt_CadastroDentistaCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField txt_CadastroDentistaCelular;
    private javax.swing.JTextField txt_CadastroDentistaCrm;
    private javax.swing.JFormattedTextField txt_CadastroDentistaDataContratacao;
    private javax.swing.JFormattedTextField txt_CadastroDentistaDataNascimento;
    private javax.swing.JTextField txt_CadastroDentistaNome;
    private javax.swing.JTextField txt_CadastroDentistaNomeUsuario;
    private javax.swing.JTextField txt_CadastroDentistaSalario;
    private javax.swing.JPasswordField txt_CadastroDentistaSenha;
    private javax.swing.JFormattedTextField txt_CadastroDentistaTelefone;
    // End of variables declaration//GEN-END:variables

    public JButton getBtn_CadastroDentistaFechar() {
        return btn_CadastroDentistaFechar;
    }

    public void setBtn_CadastroDentistaFechar(JButton btn_CadastroDentistaFechar) {
        this.btn_CadastroDentistaFechar = btn_CadastroDentistaFechar;
    }

    public JButton getBtn_CadastroDentistaLimpar() {
        return btn_CadastroDentistaLimpar;
    }

    public void setBtn_CadastroDentistaLimpar(JButton btn_CadastroDentistaLimpar) {
        this.btn_CadastroDentistaLimpar = btn_CadastroDentistaLimpar;
    }

    public JButton getBtnt_CadastroDentistaCadastrar() {
        return btnt_CadastroDentistaCadastrar;
    }

    public void setBtnt_CadastroDentistaCadastrar(JButton btnt_CadastroDentistaCadastrar) {
        this.btnt_CadastroDentistaCadastrar = btnt_CadastroDentistaCadastrar;
    }

    public JFormattedTextField getTxt_CadastroDentistaCelular() {
        return txt_CadastroDentistaCelular;
    }

    public void setTxt_CadastroDentistaCelular(JFormattedTextField txt_CadastroDentistaCelular) {
        this.txt_CadastroDentistaCelular = txt_CadastroDentistaCelular;
    }

    public JFormattedTextField getTxt_CadastroDentistaDataContratacao() {
        return txt_CadastroDentistaDataContratacao;
    }

    public void setTxt_CadastroDentistaDataContratacao(JFormattedTextField txt_CadastroDentistaDataContratacao) {
        this.txt_CadastroDentistaDataContratacao = txt_CadastroDentistaDataContratacao;
    }

    public JTextField getTxt_CadastroDentistaCrm() {
        return txt_CadastroDentistaCrm;
    }

    public void setTxt_CadastroDentistaCrm(JTextField txt_CadastroDentistaDataCrm) {
        this.txt_CadastroDentistaCrm = txt_CadastroDentistaDataCrm;
    }

    public JFormattedTextField getTxt_CadastroDentistaDataNascimento() {
        return txt_CadastroDentistaDataNascimento;
    }

    public void setTxt_CadastroDentistaDataNascimento(JFormattedTextField txt_CadastroDentistaDataNascimento) {
        this.txt_CadastroDentistaDataNascimento = txt_CadastroDentistaDataNascimento;
    }

    public JTextField getTxt_CadastroDentistaNome() {
        return txt_CadastroDentistaNome;
    }

    public void setTxt_CadastroDentistaNome(JTextField txt_CadastroDentistaNome) {
        this.txt_CadastroDentistaNome = txt_CadastroDentistaNome;
    }

    public JTextField getTxt_CadastroDentistaNomeUsuario() {
        return txt_CadastroDentistaNomeUsuario;
    }

    public void setTxt_CadastroDentistaNomeUsuario(JTextField txt_CadastroDentistaNomeUsuario) {
        this.txt_CadastroDentistaNomeUsuario = txt_CadastroDentistaNomeUsuario;
    }

    public JTextField getTxt_CadastroDentistaSalario() {
        return txt_CadastroDentistaSalario;
    }

    public void setTxt_CadastroDentistaSalario(JTextField txt_CadastroDentistaSalario) {
        this.txt_CadastroDentistaSalario = txt_CadastroDentistaSalario;
    }

    public JPasswordField getTxt_CadastroDentistaSenha() {
        return txt_CadastroDentistaSenha;
    }

    public void setTxt_CadastroDentistaSenha(JPasswordField txt_CadastroDentistaSenha) {
        this.txt_CadastroDentistaSenha = txt_CadastroDentistaSenha;
    }

    public JFormattedTextField getTxt_CadastroDentistaTelefone() {
        return txt_CadastroDentistaTelefone;
    }

    public void setTxt_CadastroDentistaTelefone(JFormattedTextField txt_CadastroDentistaTelefone) {
        this.txt_CadastroDentistaTelefone = txt_CadastroDentistaTelefone;
    }


    
}
