/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ighor.view;

import com.ighor.control.CadastroProcedimentoControl;
import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Ighor Alves
 */
public class CadastroProcedimentoView extends javax.swing.JFrame {

    private final CadastroProcedimentoControl control;

    /**
     * Creates new form CadastroProcedimentoView
     */
    public CadastroProcedimentoView() {
        initComponents();
        control = new CadastroProcedimentoControl(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_CadastroProcedimentoCadastrar = new javax.swing.JButton();
        btn_CadastroProcedimentoLimpar = new javax.swing.JButton();
        btn_CadastroProcedimentoFechar = new javax.swing.JButton();
        txt_CadastroProcedimentoNome = new javax.swing.JTextField();
        txt_CadastroProcedimentoDescricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_CadastroProcedimentoValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_CadastroProcedimentoCadastrar.setText("Cadastrar");
        btn_CadastroProcedimentoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastroProcedimentoCadastrarActionPerformed(evt);
            }
        });

        btn_CadastroProcedimentoLimpar.setText("Limpar");
        btn_CadastroProcedimentoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastroProcedimentoLimparActionPerformed(evt);
            }
        });

        btn_CadastroProcedimentoFechar.setText("Fechar");
        btn_CadastroProcedimentoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastroProcedimentoFecharActionPerformed(evt);
            }
        });

        jLabel1.setText("Cadastro de Procedimento");

        jLabel2.setText("Nome:");

        jLabel3.setText("Descrição:");

        jLabel4.setText("Valor Sugerido:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btn_CadastroProcedimentoCadastrar)
                        .addGap(66, 66, 66)
                        .addComponent(btn_CadastroProcedimentoLimpar)
                        .addGap(62, 62, 62)
                        .addComponent(btn_CadastroProcedimentoFechar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_CadastroProcedimentoNome, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(txt_CadastroProcedimentoDescricao)
                            .addComponent(txt_CadastroProcedimentoValor))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_CadastroProcedimentoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(txt_CadastroProcedimentoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_CadastroProcedimentoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CadastroProcedimentoCadastrar)
                    .addComponent(btn_CadastroProcedimentoLimpar)
                    .addComponent(btn_CadastroProcedimentoFechar))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CadastroProcedimentoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastroProcedimentoCadastrarActionPerformed
        // TODO add your handling code here:
        control.cadastrarProcimento();
    }//GEN-LAST:event_btn_CadastroProcedimentoCadastrarActionPerformed

    private void btn_CadastroProcedimentoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastroProcedimentoLimparActionPerformed
        // TODO add your handling code here:
        control.limparTela();
    }//GEN-LAST:event_btn_CadastroProcedimentoLimparActionPerformed

    private void btn_CadastroProcedimentoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastroProcedimentoFecharActionPerformed
        // TODO add your handling code here:
        control.voltarMenuPrincipal();
    }//GEN-LAST:event_btn_CadastroProcedimentoFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProcedimentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProcedimentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProcedimentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProcedimentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProcedimentoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CadastroProcedimentoCadastrar;
    private javax.swing.JButton btn_CadastroProcedimentoFechar;
    private javax.swing.JButton btn_CadastroProcedimentoLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_CadastroProcedimentoDescricao;
    private javax.swing.JTextField txt_CadastroProcedimentoNome;
    private javax.swing.JTextField txt_CadastroProcedimentoValor;
    // End of variables declaration//GEN-END:variables

    public JButton getBtn_CadastroProcedimentoCadastrar() {
        return btn_CadastroProcedimentoCadastrar;
    }

    public void setBtn_CadastroProcedimentoCadastrar(JButton btn_CadastroProcedimentoCadastrar) {
        this.btn_CadastroProcedimentoCadastrar = btn_CadastroProcedimentoCadastrar;
    }

    public JButton getBtn_CadastroProcedimentoFechar() {
        return btn_CadastroProcedimentoFechar;
    }

    public void setBtn_CadastroProcedimentoFechar(JButton btn_CadastroProcedimentoFechar) {
        this.btn_CadastroProcedimentoFechar = btn_CadastroProcedimentoFechar;
    }

    public JButton getBtn_CadastroProcedimentoLimpar() {
        return btn_CadastroProcedimentoLimpar;
    }

    public void setBtn_CadastroProcedimentoLimpar(JButton btn_CadastroProcedimentoLimpar) {
        this.btn_CadastroProcedimentoLimpar = btn_CadastroProcedimentoLimpar;
    }

    public JTextField getTxt_CadastroProcedimentoDescricao() {
        return txt_CadastroProcedimentoDescricao;
    }

    public void setTxt_CadastroProcedimentoDescricao(JTextField txt_CadastroProcedimentoDescricao) {
        this.txt_CadastroProcedimentoDescricao = txt_CadastroProcedimentoDescricao;
    }

    public JTextField getTxt_CadastroProcedimentoNome() {
        return txt_CadastroProcedimentoNome;
    }

    public void setTxt_CadastroProcedimentoNome(JTextField txt_CadastroProcedimentoNome) {
        this.txt_CadastroProcedimentoNome = txt_CadastroProcedimentoNome;
    }

    public JTextField getTxt_CadastroProcedimentoValor() {
        return txt_CadastroProcedimentoValor;
    }

    public void setTxt_CadastroProcedimentoValor(JTextField txt_CadastroProcedimentoValor) {
        this.txt_CadastroProcedimentoValor = txt_CadastroProcedimentoValor;
    }










}
