/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ighor.view;

import com.ighor.control.CadastroAtendenteControl;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Ighor Alves
 */
public class CadastroAtendenteView extends javax.swing.JFrame {

    private final CadastroAtendenteControl control;

    /**
     * Creates new form CadastroAtendente
     */
    public CadastroAtendenteView() {
        initComponents();
        control = new CadastroAtendenteControl(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_CadastroAtendenteNome = new javax.swing.JTextField();
        txt_CadastroAtendenteNomeUsuario = new javax.swing.JTextField();
        txt_CadastroAtendenteSenha = new javax.swing.JPasswordField();
        txt_CadastroAtendenteSalario = new javax.swing.JTextField();
        txt_CadastroAtendenteTelefone = new javax.swing.JFormattedTextField();
        txt_CadastroAtendenteCelular = new javax.swing.JFormattedTextField();
        txt_CadastroAtendenteDataNascimento = new javax.swing.JFormattedTextField();
        txt_CadastroAtendenteDataContratacao = new javax.swing.JFormattedTextField();
        btn_CadastroAtendenteCadastrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cadastro de Atendente");

        jLabel2.setText("Nome Completo:");

        jLabel3.setText("Nome de Usuario:");

        jLabel4.setText("Senha:");

        jLabel5.setText("Salario:");

        jLabel6.setText("Telefone:");

        jLabel7.setText("Celular:");

        jLabel8.setText("Data de Nascimento:");

        jLabel9.setText("Data de Contratação:");

        btn_CadastroAtendenteCadastrar.setText("Cadastrar");
        btn_CadastroAtendenteCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastroAtendenteCadastrarActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar");

        jButton3.setText("Fechar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_CadastroAtendenteNome)
                            .addComponent(txt_CadastroAtendenteNomeUsuario)
                            .addComponent(txt_CadastroAtendenteSenha)
                            .addComponent(txt_CadastroAtendenteSalario)
                            .addComponent(txt_CadastroAtendenteTelefone)
                            .addComponent(txt_CadastroAtendenteCelular)
                            .addComponent(txt_CadastroAtendenteDataNascimento)
                            .addComponent(txt_CadastroAtendenteDataContratacao, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btn_CadastroAtendenteCadastrar)
                        .addGap(66, 66, 66)
                        .addComponent(jButton2)
                        .addGap(62, 62, 62)
                        .addComponent(jButton3)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_CadastroAtendenteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(txt_CadastroAtendenteNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_CadastroAtendenteSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_CadastroAtendenteSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_CadastroAtendenteTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_CadastroAtendenteCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_CadastroAtendenteDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_CadastroAtendenteDataContratacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CadastroAtendenteCadastrar)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CadastroAtendenteCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastroAtendenteCadastrarActionPerformed
        // TODO add your handling code here:
        control.cadastrarAtendente();
    }//GEN-LAST:event_btn_CadastroAtendenteCadastrarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        control.voltarMenuPrincipal();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAtendenteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAtendenteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAtendenteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAtendenteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAtendenteView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CadastroAtendenteCadastrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField txt_CadastroAtendenteCelular;
    private javax.swing.JFormattedTextField txt_CadastroAtendenteDataContratacao;
    private javax.swing.JFormattedTextField txt_CadastroAtendenteDataNascimento;
    private javax.swing.JTextField txt_CadastroAtendenteNome;
    private javax.swing.JTextField txt_CadastroAtendenteNomeUsuario;
    private javax.swing.JTextField txt_CadastroAtendenteSalario;
    private javax.swing.JPasswordField txt_CadastroAtendenteSenha;
    private javax.swing.JFormattedTextField txt_CadastroAtendenteTelefone;
    // End of variables declaration//GEN-END:variables

    public JButton getBtn_CadastroAtendenteCadastrar() {
        return btn_CadastroAtendenteCadastrar;
    }

    public void setBtn_CadastroAtendenteCadastrar(JButton btn_CadastroAtendenteCadastrar) {
        this.btn_CadastroAtendenteCadastrar = btn_CadastroAtendenteCadastrar;
    }

    public JButton getBtn_CadastroAtendenteFechar() {
        return jButton3;
    }

    public void setBtn_CadastroAtendenteFechar(JButton btn_CadastroAtendenteFechar) {
        this.jButton3 = btn_CadastroAtendenteFechar;
    }

    public JButton getBtn_CadastroAtendenteLimpar() {
        return jButton2;
    }

    public void setBtn_CadastroAtendenteLimpar(JButton btn_CadastroAtendenteLimpar) {
        this.jButton2 = btn_CadastroAtendenteLimpar;
    }

    public JFormattedTextField getTxt_CadastroAtendenteCelular() {
        return txt_CadastroAtendenteCelular;
    }

    public void setTxt_CadastroAtendenteCelular(JFormattedTextField txt_CadastroAtendenteCelular) {
        this.txt_CadastroAtendenteCelular = txt_CadastroAtendenteCelular;
    }

    public JFormattedTextField getTxt_CadastroAtendenteDataContratacao() {
        return txt_CadastroAtendenteDataContratacao;
    }

    public void setTxt_CadastroAtendenteDataContratacao(JFormattedTextField txt_CadastroAtendenteDataContratacao) {
        this.txt_CadastroAtendenteDataContratacao = txt_CadastroAtendenteDataContratacao;
    }

    public JFormattedTextField getTxt_CadastroAtendenteDataNascimento() {
        return txt_CadastroAtendenteDataNascimento;
    }

    public void setTxt_CadastroAtendenteDataNascimento(JFormattedTextField txt_CadastroAtendenteDataNascimento) {
        this.txt_CadastroAtendenteDataNascimento = txt_CadastroAtendenteDataNascimento;
    }

    public JTextField getTxt_CadastroAtendenteNome() {
        return txt_CadastroAtendenteNome;
    }

    public void setTxt_CadastroAtendenteNome(JTextField txt_CadastroAtendenteNome) {
        this.txt_CadastroAtendenteNome = txt_CadastroAtendenteNome;
    }

    public JTextField getTxt_CadastroAtendenteNomeUsuario() {
        return txt_CadastroAtendenteNomeUsuario;
    }

    public void setTxt_CadastroAtendenteNomeUsuario(JTextField txt_CadastroAtendenteNomeUsuario) {
        this.txt_CadastroAtendenteNomeUsuario = txt_CadastroAtendenteNomeUsuario;
    }

    public JTextField getTxt_CadastroAtendenteSalario() {
        return txt_CadastroAtendenteSalario;
    }

    public void setTxt_CadastroAtendenteSalario(JTextField txt_CadastroAtendenteSalario) {
        this.txt_CadastroAtendenteSalario = txt_CadastroAtendenteSalario;
    }

    public JPasswordField getTxt_CadastroAtendenteSenha() {
        return txt_CadastroAtendenteSenha;
    }

    public void setTxt_CadastroAtendenteSenha(JPasswordField txt_CadastroAtendenteSenha) {
        this.txt_CadastroAtendenteSenha = txt_CadastroAtendenteSenha;
    }

    public JFormattedTextField getTxt_CadastroAtendenteTelefone() {
        return txt_CadastroAtendenteTelefone;
    }

    public void setTxt_CadastroAtendenteTelefone(JFormattedTextField txt_CadastroAtendenteTelefone) {
        this.txt_CadastroAtendenteTelefone = txt_CadastroAtendenteTelefone;
    }

    

}
