/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ighor.view;

import com.ighor.control.ListaPacienteControl;
import java.sql.Date;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Ighor Alves
 */
public class ListaPacienteView extends javax.swing.JFrame {

    //Eu quero implementar a possibilidade de vc clicar na tabela e o codigo ir para a form, mas só se isso for true
    private boolean paraMarcarConsulta=false;
    private ListaPacienteControl control;

    /**
     * Creates new form ListarPacientesView
     */
    public ListaPacienteView() {
        initComponents();
        control = new ListaPacienteControl(this);
        iniciar();
    }

    ListaPacienteView(boolean paraMarcarConsulta) {
        this.paraMarcarConsulta = paraMarcarConsulta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_ListarPacienteTexto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ListarPacienteDados = new javax.swing.JTable();
        btn_ListarPacienteBuscar = new javax.swing.JButton();
        btn_ListarPacienteFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Lista de Paciente Cadastrados");

        jLabel2.setText("Pesquisar por nome:");

        tbl_ListarPacienteDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "CPF", "Telefone", "Celular", "Data de Nascimento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_ListarPacienteDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ListarPacienteDadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_ListarPacienteDados);

        btn_ListarPacienteBuscar.setText("Buscar");
        btn_ListarPacienteBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ListarPacienteBuscarActionPerformed(evt);
            }
        });

        btn_ListarPacienteFechar.setText("Fechar");
        btn_ListarPacienteFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ListarPacienteFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(306, 306, 306))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(btn_ListarPacienteBuscar)
                                .addGap(76, 76, 76)
                                .addComponent(btn_ListarPacienteFechar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_ListarPacienteTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_ListarPacienteTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ListarPacienteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ListarPacienteFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ListarPacienteBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ListarPacienteBuscarActionPerformed
        // TODO add your handling code here:
        control.buscarPaciente();
    }//GEN-LAST:event_btn_ListarPacienteBuscarActionPerformed

    private void btn_ListarPacienteFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ListarPacienteFecharActionPerformed
        // TODO add your handling code here:
        if(paraMarcarConsulta){
            this.dispose();
        } else {
            control.voltarMenuPrincipal();
        }
    }//GEN-LAST:event_btn_ListarPacienteFecharActionPerformed

    private void tbl_ListarPacienteDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ListarPacienteDadosMouseClicked

    }//GEN-LAST:event_tbl_ListarPacienteDadosMouseClicked

    private void iniciar() {
        control.iniciarTabela();
    }




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaPacienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaPacienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaPacienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaPacienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaPacienteView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ListarPacienteBuscar;
    private javax.swing.JButton btn_ListarPacienteFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_ListarPacienteDados;
    private javax.swing.JTextField txt_ListarPacienteTexto;
    // End of variables declaration//GEN-END:variables

    public boolean isParaMarcarConsulta() {
        return paraMarcarConsulta;
    }

    public void setParaMarcarConsulta(boolean paraMarcarConsulta) {
        this.paraMarcarConsulta = paraMarcarConsulta;
    }

    public JButton getBtn_ListarPacienteBuscar() {
        return btn_ListarPacienteBuscar;
    }

    public void setBtn_ListarPacienteBuscar(JButton btn_ListarPacienteBuscar) {
        this.btn_ListarPacienteBuscar = btn_ListarPacienteBuscar;
    }

    public JButton getBtn_ListarPacienteFechar() {
        return btn_ListarPacienteFechar;
    }

    public void setBtn_ListarPacienteFechar(JButton btn_ListarPacienteFechar) {
        this.btn_ListarPacienteFechar = btn_ListarPacienteFechar;
    }

    public JTable getTbl_ListarPacienteDados() {
        return tbl_ListarPacienteDados;
    }

    public void setTbl_ListarPacienteDados(JTable tbl_ListarPacienteDados) {
        this.tbl_ListarPacienteDados = tbl_ListarPacienteDados;
    }

    public JTextField getTxt_ListarPacienteTexto() {
        return txt_ListarPacienteTexto;
    }

    public void setTxt_ListarPacienteTexto(JTextField txt_ListarPacienteTexto) {
        this.txt_ListarPacienteTexto = txt_ListarPacienteTexto;
    }





        
}
