/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ighor.view;

import com.ighor.control.MarcarConsultaControl;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Ighor Alves
 */
public class MarcarConsultaView extends javax.swing.JFrame {

    private final MarcarConsultaControl control;

    /**
     * Creates new form MarcarConsultaView
     */
    public MarcarConsultaView() {
        initComponents();
        control = new MarcarConsultaControl(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_MarcarConsultaCodPaciente = new javax.swing.JTextField();
        txt_MarcarConsultaCodDentista = new javax.swing.JTextField();
        txt_MarcarConsultaData = new javax.swing.JFormattedTextField();
        txt_MarcarConsultaHorario = new javax.swing.JFormattedTextField();
        txt_MarcarConsultaCodProcedimento = new javax.swing.JTextField();
        txt_MarcarConsultaValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_MarcarConsultaDescricao = new javax.swing.JTextArea();
        btn_MarcarConsultaBuscarPaciente = new javax.swing.JButton();
        btn_MarcarConsultaBuscarDentista = new javax.swing.JButton();
        btn_MarcarConsultaBuscarProcedimento = new javax.swing.JButton();
        btn_MarcarConsultaAgendar = new javax.swing.JButton();
        btn_MarcarConsultaLimpar = new javax.swing.JButton();
        btn_MarcarConsultaCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Agendamento");

        jLabel2.setText("Data da Consulta:");

        jLabel3.setText("Horario da Consulta:");

        jLabel4.setText("Procedimento:");

        jLabel5.setText("Valor:");

        jLabel6.setText("Codigo do Paciente");

        jLabel8.setText("Codigo do Dentista:");

        jLabel9.setText("Descricao:");

        txt_MarcarConsultaDescricao.setColumns(20);
        txt_MarcarConsultaDescricao.setRows(5);
        jScrollPane1.setViewportView(txt_MarcarConsultaDescricao);

        btn_MarcarConsultaBuscarPaciente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_MarcarConsultaBuscarPaciente.setText("Buscar");
        btn_MarcarConsultaBuscarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_MarcarConsultaBuscarPacienteMouseClicked(evt);
            }
        });
        btn_MarcarConsultaBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MarcarConsultaBuscarPacienteActionPerformed(evt);
            }
        });

        btn_MarcarConsultaBuscarDentista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_MarcarConsultaBuscarDentista.setText("Buscar");

        btn_MarcarConsultaBuscarProcedimento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_MarcarConsultaBuscarProcedimento.setText("Buscar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_MarcarConsultaData, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_MarcarConsultaValor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                        .addComponent(txt_MarcarConsultaCodProcedimento, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_MarcarConsultaCodDentista, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_MarcarConsultaCodPaciente, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn_MarcarConsultaBuscarDentista)
                                        .addComponent(btn_MarcarConsultaBuscarProcedimento)
                                        .addComponent(btn_MarcarConsultaBuscarPaciente))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(183, 183, 183))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_MarcarConsultaHorario)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))))
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_MarcarConsultaCodPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_MarcarConsultaBuscarPaciente))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_MarcarConsultaCodDentista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_MarcarConsultaBuscarDentista))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_MarcarConsultaCodProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_MarcarConsultaBuscarProcedimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_MarcarConsultaValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_MarcarConsultaData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_MarcarConsultaHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btn_MarcarConsultaAgendar.setText("Agendar");
        btn_MarcarConsultaAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MarcarConsultaAgendarActionPerformed(evt);
            }
        });

        btn_MarcarConsultaLimpar.setText("Limpar");
        btn_MarcarConsultaLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MarcarConsultaLimparActionPerformed(evt);
            }
        });

        btn_MarcarConsultaCancelar.setText("Voltar");
        btn_MarcarConsultaCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MarcarConsultaCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(btn_MarcarConsultaAgendar)
                .addGap(39, 39, 39)
                .addComponent(btn_MarcarConsultaLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btn_MarcarConsultaCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_MarcarConsultaAgendar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_MarcarConsultaLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_MarcarConsultaCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 42, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MarcarConsultaCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MarcarConsultaCancelarActionPerformed
        // TODO add your handling code here:
        MenuAtendenteView mav = new MenuAtendenteView();
        mav.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_MarcarConsultaCancelarActionPerformed

    private void btn_MarcarConsultaLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MarcarConsultaLimparActionPerformed
        // TODO add your handling code here:
        control.limpar();
    }//GEN-LAST:event_btn_MarcarConsultaLimparActionPerformed

    private void btn_MarcarConsultaAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MarcarConsultaAgendarActionPerformed
        // TODO add your handling code here:
        control.marcarConsulta();
    }//GEN-LAST:event_btn_MarcarConsultaAgendarActionPerformed

    private void btn_MarcarConsultaBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MarcarConsultaBuscarPacienteActionPerformed

    }//GEN-LAST:event_btn_MarcarConsultaBuscarPacienteActionPerformed

    private void btn_MarcarConsultaBuscarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MarcarConsultaBuscarPacienteMouseClicked
        // TODO add your handling code here:
        control.abrirListaPacientes();
    }//GEN-LAST:event_btn_MarcarConsultaBuscarPacienteMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarcarConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarcarConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarcarConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarcarConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarcarConsultaView().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_MarcarConsultaAgendar;
    private javax.swing.JButton btn_MarcarConsultaBuscarDentista;
    private javax.swing.JButton btn_MarcarConsultaBuscarPaciente;
    private javax.swing.JButton btn_MarcarConsultaBuscarProcedimento;
    private javax.swing.JButton btn_MarcarConsultaCancelar;
    private javax.swing.JButton btn_MarcarConsultaLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_MarcarConsultaCodDentista;
    private javax.swing.JTextField txt_MarcarConsultaCodPaciente;
    private javax.swing.JTextField txt_MarcarConsultaCodProcedimento;
    private javax.swing.JFormattedTextField txt_MarcarConsultaData;
    private javax.swing.JTextArea txt_MarcarConsultaDescricao;
    private javax.swing.JFormattedTextField txt_MarcarConsultaHorario;
    private javax.swing.JTextField txt_MarcarConsultaValor;
    // End of variables declaration//GEN-END:variables

    public JButton getBtn_MarcarConsultaAgendar() {
        return btn_MarcarConsultaAgendar;
    }

    public void setBtn_MarcarConsultaAgendar(JButton btn_MarcarConsultaAgendar) {
        this.btn_MarcarConsultaAgendar = btn_MarcarConsultaAgendar;
    }

    public JButton getBtn_MarcarConsultaBuscarDentista() {
        return btn_MarcarConsultaBuscarDentista;
    }

    public void setBtn_MarcarConsultaBuscarDentista(JButton btn_MarcarConsultaBuscarDentista) {
        this.btn_MarcarConsultaBuscarDentista = btn_MarcarConsultaBuscarDentista;
    }

    public JButton getBtn_MarcarConsultaBuscarPaciente() {
        return btn_MarcarConsultaBuscarPaciente;
    }

    public void setBtn_MarcarConsultaBuscarPaciente(JButton btn_MarcarConsultaBuscarPaciente) {
        this.btn_MarcarConsultaBuscarPaciente = btn_MarcarConsultaBuscarPaciente;
    }

    public JButton getBtn_MarcarConsultaBuscarProcedimento() {
        return btn_MarcarConsultaBuscarProcedimento;
    }

    public void setBtn_MarcarConsultaBuscarProcedimento(JButton btn_MarcarConsultaBuscarProcedimento) {
        this.btn_MarcarConsultaBuscarProcedimento = btn_MarcarConsultaBuscarProcedimento;
    }

    public JButton getBtn_MarcarConsultaCancelar() {
        return btn_MarcarConsultaCancelar;
    }

    public void setBtn_MarcarConsultaCancelar(JButton btn_MarcarConsultaCancelar) {
        this.btn_MarcarConsultaCancelar = btn_MarcarConsultaCancelar;
    }

    public JButton getBtn_MarcarConsultaLimpar() {
        return btn_MarcarConsultaLimpar;
    }

    public void setBtn_MarcarConsultaLimpar(JButton btn_MarcarConsultaLimpar) {
        this.btn_MarcarConsultaLimpar = btn_MarcarConsultaLimpar;
    }

    public JTextField getTxt_MarcarConsultaCodDentista() {
        return txt_MarcarConsultaCodDentista;
    }

    public void setTxt_MarcarConsultaCodDentista(JTextField txt_MarcarConsultaCodDentista) {
        this.txt_MarcarConsultaCodDentista = txt_MarcarConsultaCodDentista;
    }

    public JTextField getTxt_MarcarConsultaCodPaciente() {
        return txt_MarcarConsultaCodPaciente;
    }

    public void setTxt_MarcarConsultaCodPaciente(JTextField txt_MarcarConsultaCodPacient) {
        this.txt_MarcarConsultaCodPaciente = txt_MarcarConsultaCodPacient;
    }

    public JTextField getTxt_MarcarConsultaCodProcedimento() {
        return txt_MarcarConsultaCodProcedimento;
    }

    public void setTxt_MarcarConsultaCodProcedimento(JTextField txt_MarcarConsultaCodProcedimento) {
        this.txt_MarcarConsultaCodProcedimento = txt_MarcarConsultaCodProcedimento;
    }

    public JFormattedTextField getTxt_MarcarConsultaData() {
        return txt_MarcarConsultaData;
    }

    public void setTxt_MarcarConsultaData(JFormattedTextField txt_MarcarConsultaData) {
        this.txt_MarcarConsultaData = txt_MarcarConsultaData;
    }

    public JTextArea getTxt_MarcarConsultaDescricao() {
        return txt_MarcarConsultaDescricao;
    }

    public void setTxt_MarcarConsultaDescricao(JTextArea txt_MarcarConsultaDescricao) {
        this.txt_MarcarConsultaDescricao = txt_MarcarConsultaDescricao;
    }

    public JFormattedTextField getTxt_MarcarConsultaHorario() {
        return txt_MarcarConsultaHorario;
    }

    public void setTxt_MarcarConsultaHorario(JFormattedTextField txt_MarcarConsultaHorario) {
        this.txt_MarcarConsultaHorario = txt_MarcarConsultaHorario;
    }

    public JTextField getTxt_MarcarConsultaValor() {
        return txt_MarcarConsultaValor;
    }

    public void setTxt_MarcarConsultaValor(JTextField txt_MarcarConsultaValor) {
        this.txt_MarcarConsultaValor = txt_MarcarConsultaValor;
    }
    
    
}
